shift/accounts/urls.py
from django.urls import path
from . import views
#from shiftapp import views
app_name ='accounts'

urlpatterns =[
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('mypage/dayschoice/', views.days_choice, name='dayschoice'),
]

shift/shift/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('yoshico/', include('shiftapp.urls'))
]

shift/shiftapp/urls.py
from django.urls import path
from . import views

app_name ='shiftapp'

urlpatterns =[
    path('shift', views.makeshift, name='makeshift'),
    path('', views.yoshico, name='yoshico'),
]

shift/accounts/models.py
from django.conf import settings
from django.db import models


GENDER_CHOICES = (
    ('1', '男性'),
    ('2', '女性'),
)


class Profile(models.Model):
    name = models.CharField("ニックネーム", max_length=1)
    gender = models.CharField("性別", max_length=2, choices=GENDER_CHOICES)
    days = models.CharField("定刻出勤",max_length=100,null=True, blank=True)
    days_late = models.CharField("遅れ出勤",max_length=100,null=True, blank=True)
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)

    def __str__(self):
        return self.name

shift/accounts/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class LoginForm(AuthenticationForm):
    """ログインフォーム"""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ("name", "gender",)
        
class DaysForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ("days", "days_late",)

        

        

shift/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from .forms import LoginForm, ProfileForm, DaysForm


class Login(LoginView):
    """ログインページ"""
    form_class = LoginForm
    template_name = 'accounts/login.html'

class Logout(LoginRequiredMixin, LogoutView):
    """ログアウトページ"""
    template_name = 'accounts/login.html'


def signup(request):
    user_form = UserCreationForm(request.POST)
    profile_form = ProfileForm(request.POST)  #{{ form.as_p }}の部分で表示される
    if request.method == 'POST' and user_form.is_valid() and profile_form.is_valid():

        user = user_form.save(commit=False)
        user.is_active = True
        user.save()

        profile = profile_form.save(commit=False)
        profile.user = user
        profile.save()
        return redirect('../login/')

    context = {
        "user_form": user_form,
        "profile_form": profile_form,
    }

    return render(request, 'accounts/signup.html', context)



def days_choice(request):
    days = ""
    days_late = ""
    state = ""
    state_late = ""

    if not request.user.profile.days in [None, '0']:
        state = request.user.profile.days
    if not request.user.profile.days_late in [None, '0']:
        state_late = request.user.profile.days_late

    form = DaysForm(request.POST or None,initial={'days': state, 'days_late':state_late})

    if request.method == 'POST' and form.is_valid():
        obj = request.user.profile
        form = DaysForm(request.POST, instance = obj)

        form.save(commit = False)

        days = "定刻出勤可を"+str(form.cleaned_data['days'])+"日で登録"
        days_late = "遅れ出勤可を"+str(form.cleaned_data['days_late'])+"日で登録"


        if not (dayscheck(form.cleaned_data['days'],form.cleaned_data['days_late'])):
            days = "登録できませんでした。"
            days_late = "形式の間違い、または日付の重複があります。"

        else:
            if form.cleaned_data['days'] == None:
                form.days = state
                days = ""

            if form.cleaned_data['days_late'] == None:
                form.days_late = state_late
                days_late = ""

            form.save()

    params = {
        'form': form,
        'name': request.user.profile.name,
        'days': days,
        'days_late': days_late,
    }
    return render(request, 'accounts/dayschoice.html', params)



def dayscheck(days, days_late):
    notls = []
    d1 = 0
    d10 = 0
    if days == None and days_late == None:
        return True

    if days == None:
        pass
    else:
        for day in days:
            if d10 != 0 and day.isdecimal() and day.isalnum():
                return False
            elif day.isdecimal() and day.isalnum():
                if int(d1) == 0:
                    d1 = int(day)
                else:
                    d10 = d1
                    d1 = int(day)
            elif day == '.' or day == ',':
                if d10 * 10 + d1 > 31:
                    return False
                if d10 * 10 + d1 in notls:
                    return False
                notls.append(d10 * 10 + d1)
                d1 = 0
                d10 = 0
            else:
                return False
        if d10 * 10 + d1 > 31:
            return False
        elif d10 * 10 + d1 != 0:
            if d10 * 10 + d1 in notls:
                return False
            notls.append(d10 * 10 + d1)
            d1 = 0
            d10 = 0

    if days_late == None:
        pass
    else:
        for day in days_late:
            if d10 != 0 and day.isdecimal() and day.isalnum():
                return False
            elif day.isdecimal() and day.isalnum():
                if int(d1) == 0:
                    d1 = int(day)
                else:
                    d10 = d1
                    d1 = int(day)
            elif day == '.' or day == ',':
                if d10 * 10 + d1 > 31:
                    return False
                if d10 * 10 + d1 in notls:
                    return False
                notls.append(d10 * 10 + d1)
                d1 = 0
                d10 = 0
            else:
                return False
        if d10 * 10 + d1 > 31:
            return False
        elif d10 * 10 + d1 != 0:
            if d10 * 10 + d1 in notls:
                return False

    return True

shift/templates/accounts/dayschoice.html
<!DOCTYPE html>

<html lang="ja">
<head>
<meta charset="UTF-8">
<title>むさしふと</title>
<style type="text/css">
  #id_days, #id_days_late {
    width: 500px;
    height: 50px;
  }
  button {
    width: 100px;
    height: 50px;
  }
</style>
</head>
<body>
<h2>"{{ name }}"</h2>さんようこそ
<table  border="1" style="border-collapse: collapse">

<br>
<p><font size="5">入れる日にちを下の枠に<br>
（例）1.2.3.10.11.13.25.26<br>
    の様に半角数字を. または ,で区切って記入して下さい。</font></p>

<form method="post">{% csrf_token %}
{{ form.as_p }}
<button type="submit">送信</button>
</form>
<p>{{ days }}</p>
<p>{{ days_late }}</p>
<br>


<p>23日まで変更可能です。</p>
<p>全員の登録状況は、よしこさんのページで確認できます。</p>
<button type="submit"><a href="../../logout/">ログアウト</a></button>

</body>
</html>

shift/templates/accounts/login.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>むさしふと</title>
<style type="text/css">
  #id_user, #id_password {
    width: 500px;
    height: 50px;
  }
  button {
    width: 100px;
    height: 50px;
  }
</style>
</head>
<body class="hold-transition login-page">
  <h1>むさしふと</h1>
  
  <h2>ログイン</h2>

  <form action="" method="POST"> 
    {% csrf_token %}
    {% for field in form %}
      {{ field }} 
    {% endfor %}

    {% for error in form.non_field_errors %}    
      <p>{{ error }}</p>
    {% endfor %}

    <button type="submit">ログイン</button>
  </form>
  <br>
  <h2>アカウント登録</h2>
  <p>アカウントをお持ちでない方は<a href="../signup/">こちら</a>からアカウント登録をしてください。</p>
  <br>
  <h2>よしこさん</h2>
  <p>よしこさんは<a href="{% url 'shiftapp:yoshico'%}">こちら</a></p>

</body>
</html>

shift/templates/accounts/signup.html
<!DOCTYPE html>

<html lang="ja">
<head>
<meta charset="UTF-8">
<title>むさしふと</title>
</head>
<body>
<h1>むさしふと</h1>
  <p>アカウント作成ページです。アカウントをすでにお持ちの方は<a href="../login/">こちら</a>からログインしてください。</p>
  <p>登録が成功すると自動的にログインページに移動しますので、ログインしてご利用ください。</p>
  <p>アカウント登録後ログインページに移動しない場合、アカウント作成が成功していませんので、ユーザー名を変更するか、<br>パスワードを変えるなどして再度ご登録お願いします。</p>
  <p>ニックネームは1文字で決めてください。</p>

  <h2>アカウント登録</h2>
  <form method="post">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <button type="submit">登録</button>
  </form>
<br>
<a href="../login/">戻る</a>
</body>
</html>